### ISSUE TITLE
Project sample

### ISSUE THREAD

**Issue by juliocbcotta** [nodes-vapor/jwt-keychain#10]
Hi, would you mind to provide a project sample using this repo dependence ?

**Comment by Casperhr** [comment]
@BugsBunnyBR Sure, I try to put something up

**Comment by Casperhr** [comment]
https://github.com/nodes-vapor/jwt-keychain-demo/blob/master/README.md

**Comment by juliocbcotta** [comment]
Thanks

**Comment by Casperhr** [comment]
Im updating it for the new version with your PR
