### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/jwt-keychain#18]
Take a look at https://github.com/nodes-vapor/admin-panel/blob/master/Sources/AdminPanel/Controllers/LoginController.swift#L52

Could be copy pasted in with some configs

**Comment by Casperhr** [comment]
Remember to update readme with the new configs

And also I do not understand why resetPasswordEmail & secondsToExpireResetPassword is in jwt.json? I get the issue in that a new config is not nice either :)

**Comment by pcoutinho** [comment]
Updated the Readme. Will create a new issue to refactor the jwt.json
