### ISSUE TITLE
Support OAuth flow with client token and refresh token

### ISSUE THREAD

**Issue by juliocbcotta** [nodes-vapor/jwt-keychain#23]
Hi, would be nice to have support to oauth with refresh token?
I am not quite sure about how to implement this auth format or if it is in the scope of this project, so I will let here what I think I know...

- Client token: Static token, not refreshable, used to access public APIs, used in the Authorization header;
- User token: Acquired on login, refreshable, used to access private APIs, used in the Authorization header;
 - Refresh token: refreshable when issuing new User token, used only in refresh token endpoint, never in the Authorization header;

Endpoint to login/refresh token
/api/v1/oauth

Credentials for login (may require Client token in Authorization header) 
request body:
```json
{
  "grant_type": "password",
  "email": "me@mail",
  "password": "secret"
}
```

Credentials for refresh_token (may require Client token in Authorization header) 
request body:
```json
{
  "grant_type": "refresh_token",
  "refresh_token": "blablabla"
}
```

response body:
```json
{
  "token_type": "Bearer",
  "access_token": "asdasdasdasd",
  "refresh_token": "new blablabla",
  "expires_in": 3600
}
```

Would need more config entries in `jwt.json` to allow the configuration of TTL for the refresh_token and maybe a way to list the client tokens (since they are static, they can be seem as part of the config?)

If someone could give me an input about this before I start implementing something would be nice.

**Comment by Casperhr** [comment]
Imo the package is called jwt, so lets not add other auth systems here.

There is plenty of work to do on polish this first. Check issues if you want to help out more.

And thanks for the help again

**Comment by juliocbcotta** [comment]
So.. what happens to the user when the JWT token session expires today? 
Users need to login again (email/password)?
I think your client needs to update the token before it expires, right? This is suboptimal. With refresh tokens the client can get a 401, refresh the access token and repeat the original call without having the user to input their email/password again.

All the oauth flow uses JWT tokens, so the library name still makes sense.

I will keep this idea in my backlog, let`s work in more pressing issues and maybe I just fork the project to have this done. :-D

**Comment by Casperhr** [comment]
Ok I get your point. A refresh token makes sense in that case.
But that should expire at some point also?

In my experience, you want to keep tokens running for running for a short period (high security apps) or almost forever. Like 60 days or more.

Feel free to make the PR to this package. I don't mind it having that feature. As long as we can config it

**Comment by juliocbcotta** [comment]
The refresh tokens have a TTL (time to live) bigger than the access tokens.

Something like... the access tokens 2 hours and refresh tokens 7 days. The big deal here is that both need to be kept in a secure way in the client side (which is out of the scope of this project, of course).

The idea is having these TTLs configurable when the developer deploys the app.

**Comment by steffendsommer** [comment]
Refresh + access tokens are now supported out of the box.
