### ISSUE TITLE
Default implementations for UserControllerType protocol instead of concrete class

### ISSUE THREAD

**Issue by chriscombs** [nodes-vapor/jwt-keychain#30]
`UserController`can have all of that logic put into `UserControllerType` as a default implementation (if you change a few little things). Much more swifty than subclassing. #29

**Comment by Casperhr** [comment]
Sounds fine to me, @steffendsommer any comments?

**Comment by steffendsommer** [comment]
I agree that default implementations are more Swifty, however not a silver bullet imo, e.g. using the default implementations AND applying custom stuff can be a bit tricky - this is what I referred to as not being that pretty in my PR (https://github.com/nodes-vapor/jwt-keychain/pull/28).

For example, in my current project I wanted to re-use the existing `UserController` functionality (by calling the method on `super`) and then do whatever afterwards. Using default implementations makes this a bit tricky, but maybe my use-case is an edge-case. What do you think?
