### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/jwt-keychain#34]
To make this package easier to pick up we should try to add more to the documentation such as examples and small tips and tricks (e.g. `expire = 0`)

**Comment by BrettRToomey** [comment]
👍 especially now that we have the huge email interface.

**Comment by steffendsommer** [comment]
Remember guidance about how to copy views into the project

**Comment by rasmusebbesen** [comment]
Please add instructions on how to setup the frontend routes for resetting passwords.

**Comment by rasmusebbesen** [comment]
Also add explanation on the Signer keys. (Length, type, how to generate, etc)

**Comment by siemensikkema** [comment]
closing. see #103
