### ISSUE TITLE
Making the user model as flexible as possible

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/jwt-keychain#7]
Since its hard to extend. All places where User is used. should be a generic. Maybe from config?

**Comment by juliocbcotta** [comment]
I would like to help with this and I have an idea.

How about not having a `User` model, but an `UserCredential` model that access the same `user` table?
I mean, is it possible to have two models mapping the same  database table with fluent?

The `UserCredential` would have just the auth fields mapped on it.
userId, email, password.
This approach would free the `User` model from all responsibility of authentication.

**Comment by Casperhr** [comment]
I would set up a jwt-keychain-demo-extended repo and try to check how you can override the current system, if you need to have more field on the model (new model)

Or you want your own controller, since you want to chance something
@steffendsommer said he managed to just subclass the controller. and the model is passed to auth middleware. But test it out. Also wanted to have that demo linked to the repo any ways

**Comment by Casperhr** [comment]
https://github.com/nodes-vapor/jwt-keychain-demo-advanced

**Comment by juliocbcotta** [comment]
So I cloned the jwt-keychain-demo-advanced and used as base the jwt-keychain-demo to make calls. It runs just fine.

> Or you want your own controller, since you want to chance something
@steffendsommer said he managed to just subclass the controller. and the model is passed to auth middleware.


I am able to use DI `UserController` to `UserRoutes`. This would allow the subclass to change almost any desired behavior, but  I got some trouble here.

To allow the inclusion of new authorized routes I tried something like this
from:
```
// UserRoutes
// Protected routes
        path.group(jwtAuthMiddleware, authMiddleware, protectMiddleware) { secured in
            secured.get("logout", handler: controller.logout)
            secured.patch("token", "regenerate", handler: controller.regenerate)
            secured.get("me", handler: controller.me)
        }
````

to:

```
// UserRoutes
// Protected routes
        path.group(jwtAuthMiddleware, authMiddleware, protectMiddleware) { secured in
           self.controller.setAuthorizedRoutes(secured: secured)
        }
```
and to:

```
// UserController
func setAuthorizedRoutes(secure: ????) {
           secured.get("logout", handler: controller.logout)
            secured.patch("token", "regenerate", handler: controller.regenerate)
            secured.get("me", handler: controller.me)
}
```
that would solve the problem of adding new authorized routes in subclasses, but I could not find the type to use as parameter to `setAuthorizedRoutes`. Do you guys have any clue?

**Comment by dominik-hadl** [comment]
What you'd have to do is something like this.

```
    func setAuthorizedRoutes(pathGroup: RouteGroup<Responder, Droplet>) {
        pathGroup.get("logout", handler: logout)
        pathGroup.patch("token", "regenerate", handler: regenerate)
        pathGroup.get("me", handler: me)
    }
```

However, I am not sure that explicitly defining the generic constraints on the RouteGroup is a good idea. Would rather want to see an even more generic solution. 👻

**Comment by juliocbcotta** [comment]
@nickskull, Thanks for the reply!

> Would rather want to see an even more generic solution.

So... Would you like to handle these changes? At the moment I feel that I am struggling to see what can be done in that way.

**Comment by dominik-hadl** [comment]
I think it's safe to go ahead with what I wrote for now as I am pretty confident it will work for 99% of the cases. I haven't figured out an optimal solution yet too, but let's focus on that later. You're more than welcome to handle the changes 😇  Thanks for all the help, it's really appreciated 👍

**Comment by juliocbcotta** [comment]
Ok.
Trying to compile using the `RouteGroup<Responder, Droplet>` gives me
```
jwt-keychain/Sources/JWTKeychain/Routes/UserRoutes.swift:50:9: error: ambiguous reference to member 'group(_:closure:)'
        path.group(jwtAuthMiddleware, authMiddleware, protectMiddleware) { secured in
        ^~~~
HTTPRouting.RouteBuilder:12:17: note: found this candidate
    public func group(_ path: String..., closure: (Routing.RouteGroup<Responder, Self>) -> ())
                ^
Vapor.RouteBuilder:2:17: note: found this candidate
    public func group(_ middleware: Middleware..., closure: (Routing.RouteGroup<Responder, Self>) -> ())
                ^
```
I am stuck again. Should I define a type to `path` to remove the ambiguous reference?

**Comment by dominik-hadl** [comment]
Can you please post the snippets of the related code you have? It worked on my machine, so I wonder what is different :)

**Comment by juliocbcotta** [comment]
Take a look [here](https://github.com/BugsBunnyBR/jwt-keychain/tree/separate-user-routing-from-configs), this branch does not compile and shows the approach I am implementing and the problems I am facing...
Thanks for all the help.

**Comment by BrettRToomey** [comment]
I think the user model should actually be a protocol requiring the fields loaded from JWT and then you can add generic constraints and the user should then be able to supply their own model.

**Comment by steffendsommer** [comment]
I agree with @BrettRToomey and then we should still just have some simple implementation for those who don't want to roll out their own model.

**Comment by dominik-hadl** [comment]
I completely agree, that's the best way of doing it.

**Comment by chriscombs** [comment]
Should the model here be renamed to something else then, like "BasicUser"? Kind of annoying that every project will have to come up with a different model name because this one is already using "User"

**Comment by steffendsommer** [comment]
I considered this @chriscombs, and also experimented with renaming everything to e.g. `JWTUser`, `JWTUserController` etc. however, I think the Swift approach is more to leverage on the namespaces. So if different modules defines the same type (e.g. `User`) the compiler will try to infer it automatically or if you want to pin it, you can prefix the type with the module name e.g. `JWTKeychain.User`.

**Comment by juliocbcotta** [comment]
Should [Request.user()](https://github.com/nodes-vapor/jwt-keychain/blob/master/Sources/JWTKeychain/Extensions/Request%2BUser.swift#L24) return a `UserType`?
Should `UserRoutes` be open and have methods like `setPublicRoutes`, `setAuthorizationRoutes` and `setAuthorizedRoutes`, so whoever extends `UserRoutes` is able to add new routes?

**Comment by steffendsommer** [comment]
> Should [Request.user()](https://github.com/nodes-vapor/jwt-keychain/blob/master/Sources/JWTKeychain/Extensions/Request%2BUser.swift#L24) return a UserType?

Yes, it should. The same goes for this reference in [`StoreRequest`](https://github.com/nodes-vapor/jwt-keychain/blob/77634957b5c673715b412aa9e8f0d4f909e21c5b/Sources/JWTKeychain/Requests/Api/Users/StoreRequest.swift#L14). Both were on my todo - feel free to pitch in.

As for `UserRoutes` I'm not sure actually. I don't have the clear overview of what we gain. Right now, all dependencies are passed into the `UserRoutes` so everyone should be able to setup any needed routes outside of this `RouteCollection` using the same dependencies. That was my reason for not looking into `UserRoutes` (for now at least), but maybe I'm missing something. What are your thoughts @BugsBunnyBR?

**Comment by juliocbcotta** [comment]
I think the main idea of `UserRoutes` is to separate the concern of routing and executing an (public/authorized) action  from the Controller and the Droplet, right? If so...  When a developer wants to add a new authorized route to its `UserController`, how is it done? With my limited Swift/Vapor knowledge I would extend `UserController` class , but if this route is available just after login I would need to rewrite `UserRoute` logic that selects which routes are authenticated.

**Comment by steffendsommer** [comment]
Just to follow up on my last comment. The return type in `Request.user()` has been fixed here: https://github.com/nodes-vapor/jwt-keychain/pull/31

As for the `StoreRequest`, I discussed with @BrettRToomey about abstracting the validation logic to make it a bit more flexible - I hope to be able to look at this one of the following days.

As to your comment @BugsBunnyBR, if I understand your question correctly, you can do the following at the moment:
```swift
// Instantiate the middleware.
let configuration = try JWTKeychain.Configuration(drop: drop)
let jwtAuthMiddleware = JWTKeychain.AuthMiddleware(configuration: configuration)
let authMiddleware = Auth.AuthMiddleware<JWTKeychain.User>()
let protectMiddleWare = ProtectMiddleware(
    error: Abort.custom(
        status: .unauthorized,
        message: Status.unauthorized.reasonPhrase
    )
)

// Use the JWTKeychain routes.
let userController = UserController(configuration: configuration)
drop.collection(
    try UserRoutes(
        drop: drop,
        configuration: configuration,
        jwtAuthMiddleware: jwtAuthMiddleware,
        authMiddleware: authMiddleware,
        protectMiddleware: protectMiddleWare,
        userController: userController
    )
)

// Add another protected route.
drop.group(collection: [jwtAuthMiddleware, authMiddleware, protectMiddleWare], closure: {
        authenticated in
        authenticated.get("posts", handler: PostController().getPosts)
})
```

For now, I think the most important part is to make `User` and `UserController` flexible as we can extend the routes (as above) - what do you think?

**Comment by BrettRToomey** [comment]
I took an initial pass at this with some generics. It may need some more tweaking, but I believe we are a step closer in the correct direction.
