### ISSUE TITLE
Remove password hash from JWTs

### ISSUE THREAD

**Issue by siemensikkema** [nodes-vapor/jwt-keychain#97]
Currently the full password hash is included in all tokens as a way to make sure tokens are invalidated after a password reset. Although this does not directly enable unauthorized access it does expose the hashes unnecessarily. A more secure, but still simple, system would be to store a separate value on the user object that changes on each password change which will be compared to the value in incoming tokens. This value could be a counter, a date or a UUID.

**Comment by steffendsommer** [comment]
Solved by https://github.com/nodes-vapor/jwt-keychain/pull/99 (@siemensikkema otherwise feel free to re-open)
